---
- name: Criar pasta de auth
  file:
    state: directory
    path: /home/vagrant/registry/auth

- name: Criar senhas
  htpasswd:
    path: /home/vagrant/registry/auth/htpasswd
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    crypt_scheme: bcrypt
  with_items: "{{ htpasswd_credentials }}"
  no_log: true

- name: Copiar daemon.json
  copy:
    src: daemon.json
    dest: /home/vagrant/registry/daemon.json

- name: Deploy Docker Registry Container
  docker_container:
    image: registry:2.7.1
    name: registry
    restart_policy: always
    restart: yes
    state: started
    recreate: yes
    volumes:
      - /home/vagrant/registry/daemon.json:/etc/docker/daemon.json
      - /home/vagrant/registry/certs:/certs
      - /home/vagrant/registry/auth:/auth
      - /home/vagrant/registry/repos:/var/lib/docker/
    env:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm {{ambiente}}
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # REGISTRY_HTTP_SECRET: best-secret
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.{{ambiente}}.infra.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/registry.{{ambiente}}.infra.key
      # REGISTRY_HTTP_ADDR: 0.0.0.0:443
    ports:
      - 443:443
      - 5000:5000
      - 5001:5001
      - 9323:9323

- name: Testando Docker Registry
  uri:
      url: http://{{ansible_host}}:5000/v2/
      status_code: 200
      return_content: yes
      user: registry
      password: 2Cbn2SAJaAs3
  register: test_docker_registry
  until: test_docker_registry.content == '{}'
  retries: 5
  delay: 2
  ignore_errors: yes